(defun show-dots (lst)
  (cond ((atom lst)
         (format t "~S" lst))
	(t
	 (format t "(")
	 (show-dots (car lst))
	 (format t " . ")
	 (show-dots (cdr lst))
	 (format t ")"))))

(defun show-list-content (lst)
  (cond ((and (atom lst) (not (null lst)))
	 (format t " . ~S" lst))
	((null (car lst))
	 (format t ""))
	((atom (car lst))
	 (format t " ~S" (car lst))
	 (show-list-content (cdr lst)))
	(t
	 (format t " ")
	 (show-list (car lst))
	 (show-list-content (cdr lst)))))

(defun show-list (lst)
  (cond ((atom lst)
	 (format t "~S" lst))
	((null lst)
	 (format t ""))
	((atom (car lst))
	 (format t "[~S" (car lst))
	 (show-list-content (cdr lst))
	 (format t "]"))
	(t
	 (format t "[")
	 (show-list (car lst))
	 (show-list-content (cdr lst))
	 (format t "]"))))
