(defun show-dots (lst)
  (cond ((atom lst)
         (format t "~S" lst))
	(t
	 (format t "(")
	 (show-dots (car lst))
	 (format t " . ")
	 (show-dots (cdr lst))
	 (format t ")"))))

(defun show-list-content (lst)
  (cond ((null lst)
	 nil)
	((atom lst)
	 (format t " . ~S" lst))
	(t
	 (format t " ")
	 (show-list (car lst))
	 (show-list-content (cdr lst)))))

(defun show-list (lst)
  (cond ((atom lst)
	 (format t "~S" lst))
	((null lst)
	 nil)
	(t
	 (format t "[")
	 (show-list (car lst))
	 (show-list-content (cdr lst))
	 (format t "]"))))
