(defun max-min-loop (vec start end)
  (let ((val (aref vec start)))
    (if (= (1+ start) end)
	(values val val)
	(multiple-value-bind (max-val min-val) (max-min-loop vec (1+ start) end)
	  (values (max max-val val) (min min-val val))))))

(defun max-min (vec &key (start 0) (end (length vec)))
  (if (= start end)
      (values nil nil)
      (max-min-loop vec start end)))
